### ISSUE TITLE
建议整个多协议共存

### ISSUE THREAD

**Issue by 1779587460** [yonggekkk/CF-workers-pages-vless#3]
想把不同的自选域名用在clash配置文件上，让clash自动优选，但只有meta核支持vless，而且还得手动修改配置文件很麻烦，建议甬哥整个多协议的，单VMESS也可以

**Comment by yonggekkk** [comment]
这个只能看上游大佬更新了，这几天大佬会出vmess。
但目前vless与vmess的区别，表面上看就是后者有个加密，客户端应用更广。。
