### ISSUE TITLE
电脑端能用，安卓端能成功连接但没有流量。

### ISSUE THREAD

**Issue by sztcj** [yonggekkk/CF-workers-pages-vless#4]
甬哥，按你的视频步骤，电脑端完美连接，但同样的配置到手机端v2rayNG就不行了，显示已连接，服务也成功启动，测试也连接成功延时几百这样子，但youtube打不开。优选过几次IP都不行，app也是最新的了。

**Comment by sztcj** [comment]
忘了说明一点，这个配置前段时间是可以正常使用的，就昨天开始出现这个问题，到现在依然连不上。

**Comment by yonggekkk** [comment]
NG设置-两个DNS打勾

**Comment by sztcj** [comment]
按你的方法解决问题了，感谢。
